### ISSUE TITLE
Silent data loss & corruption of unrelated row when attempting to insert duplicate value in unique column

### ISSUE THREAD

**Issue by erayd** [tflori/orm#15]
Creating and inserting a new object that collides in a unique column results in the following:
 * The row is never inserted, but does not throw an exception and appears to succeed
 * The object is altered to point at (I think) the first row in the table
 * Future updates to the object are saved to the first row in the table
 * Any previous data in the table's first row is replaced and lost without warning

I discovered and was able to reliably reproduce this bug on MariaDB (MySQL) 10.0.28, but have not tested on other database engines.

I have attached a simple test case which demonstrates the problem:
```PHP
<?php
/*---------------------- Example database ------------------------+

  SET NAMES UTF8, SQL_MODE=ANSI;

  CREATE TABLE "example" (
    "id" INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    "magic_number" INT,
    "magic_unique" INT UNIQUE
  );

  INSERT INTO "example" ("magic_number", "magic_unique")
    VALUES (1, 1), (2, 2), (3, 3);

+----------------------------------------------------------------*/

require('vendor/autoload.php');

class Example extends ORM\Entity {}

$pdo = new PDO('mysql:host=localhost;dbname=example', 'myUser', 'myPass');
$pdo->exec("SET NAMES UTF8, SQL_MODE=ANSI");

$entityManager = new ORM\EntityManager(['connection' => $pdo]);

/* At this point, data is exactly as inserted, primary key auto-set correctly
+----+--------------+--------------+
| id | magic_number | magic_unique |
+----+--------------+--------------+
|  1 |            1 |            1 |
|  2 |            2 |            2 |
|  3 |            3 |            3 |
+----+--------------+--------------+
*/

$example = new Example(['magic_number' => 4, "magic_unique" => 3], $entityManager);
$example->save();

/* No exception is thrown, despite the unique index colliding and causing the
 * insert to fail. According to var_dump(), $example now seems to be linked to
 * row #1 - this should not happen!
+----+--------------+--------------+
| id | magic_number | magic_unique |
+----+--------------+--------------+
|  1 |            1 |            1 |
|  2 |            2 |            2 |
|  3 |            3 |            3 |
+----+--------------+--------------+
*/


$example->magicNumber = 4;
$example->save();

/* Row #1 is updated, despite having nothing whatsoever to do with the object
 * that we created. This is probably because $example was left pointing at row #1
 * after the magic_unique collision. Once again, there is no error or exception
 * thrown, so the end result of this is silent data corruption.
+----+--------------+--------------+
| id | magic_number | magic_unique |
+----+--------------+--------------+
|  1 |            4 |            1 |
|  2 |            2 |            2 |
|  3 |            3 |            3 |
+----+--------------+--------------+
*/
```

**Comment by tflori** [comment]
wow, looks like an early bug. thanks for the report - I will have a look into it

**Comment by tflori** [comment]
ah - now I know it is not a bug. the simplicity on this library is that it is using what php gives us. it counts on the settings `$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);`. then you will get an `PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3' for key 'magic_unique'` what is absolutely correct.

**Comment by tflori** [comment]
a much simpler way to use it is this way:
```php
<?php
$em = new ORM\EntityManager([
  'connection' => ['mysql', 'example', 'myUser', 'myPass']
]);
```

other settings are set by default (`SET sql_mode ='ANSI_QUOTES', NAMES utf8`)

**Comment by erayd** [comment]
Thanks for the speedy follow-up - you're really into it! :-) Will this setting be automatically applied by the ORM going forward, or will I need to set this myself? 

If the ORM will not be setting it, then it may be worth putting a note in the documentation about needing this, due to the possibility of accidentally losing data if it's not set - I had assumed that the ORM would take care of its own error handling requirements, and didn't realise that it was relying on a particular PDO error mode being set by the user in order for it to work correctly.

**Comment by tflori** [comment]
I will force this settings in `setConnection` (it is used from construct as well).

**Comment by erayd** [comment]
Wonderful - thanks :-).
