### ISSUE TITLE
Many-to-many relations column key seems to not be possible in camelCase

### ISSUE THREAD

**Issue by FloKnapp** [tflori/orm#23]
Hi T.,

i currently experienced a strange behavior and i'm not sure if i'd doing something wrong.

I have the following setup:

user | userrole | roles
------|------------|-------
id | userId | id
firstname  | roleId | name
lastname | | 
... | | 

The relation definition for the UserEntity:
`protected static $relations = [ 'roles' => [RoleEntity::class, ['id' => 'userId'], 'users', 'userrole']];`

The relation definition for the RoleEntity:
`protected static $relations = ['users' => [Entity::class, ['id' => 'roleId'], 'roles', 'userrole']];`

Now i expect that everything went fine and i can access the relations... but i got an exception about non existing column "roleId".

Solution: I changed the defintion from
`protected static $relations = [ 'roles' => [RoleEntity::class, ['id' => 'userId'], 'users', 'userrole']];`
to
`protected static $relations = [ 'roles' => [RoleEntity::class, ['id' => 'user_id'], 'users', 'userrole']];`
and it works (notice the snake case definition of "roleId" in the [reference] block.

Thank you in advance for any help or explanation!

Regards,
Flo

**Comment by tflori** [comment]
Please have a look in [the docs](https://tflori.github.io/orm/relationDefinition.html) as they say: 
> ATTENTION: Because we don’t have an entity in the middle the foreign key column in the association table has to be the column name and not the variable name.

suggest a better text if this is unclear :smiley:

**Comment by FloKnapp** [comment]
Oh! Thank you for resolving this "issue". Now i get it right... i read it a bunch of times but i accidently switched the meaning of "column name" with "table name". I should make more breaks :+1:

Thank you again for your fast response :100:
