### ISSUE TITLE
Key missing when fetching an entity

### ISSUE THREAD

**Issue by FloKnapp** [tflori/orm#28]
Hello :-),

i currently encountered a strange issue... maybe it is my fault but in your class \Orm\Entity there is a function where the previous stored data is established to be different. If the property 'data' is empty, there is an array key access on an empty dataset. I think you wanted to suppress that with the \@-Operator :P. Maybe this type of existence check or suppressing the error isn't possible in PHP7 anymore...

https://github.com/FloKnapp/orm/blob/feature-keyError/src/Entity.php#L469

It's getting more and more confusing... My PHP interpreter raises a "Notice: Undefined index: login in..."
But if i use the \@-Operator it's gone in https://3v4l.org/G8v9U

It's just when i'm running this code within my implementation...

![message](https://cloud.githubusercontent.com/assets/3774820/24609137/e443e0b8-1879-11e7-9ac0-843ad48ba043.png)

**Comment by tflori** [comment]
@FloKnapp weird. I don't know any feature to disable the stfu operator. may be it is possible by setting the error handler to something that throws the notice as exception.. I will give it a try and also find a more clean way to suppress a error message here..

**Comment by tflori** [comment]
https://3v4l.org/UC11F

**Comment by tflori** [comment]
@FloKnapp try using v1.1.1 it should work there

**Comment by FloKnapp** [comment]
@tflori Thank you very much! Now this didn't cause an error any more :+1: 

It's annoying if you want to make it perfect for everyone... my quickfix solution didnt solve that issue too, because it never jumps into the onChange-Event. I'm glad you found a solution :1st_place_medal: 

Thank you!
