### ISSUE TITLE
DateTime Handling in SQLite (and maybe Type handling in general)

### ISSUE THREAD

**Issue by splitbrain** [tflori/orm#42]
It seems that datetime handling doesn't work as expected for SQLite databases. 

My column definition looks like this:
```
"dt" DATETIME NOT NULL,
```

Trying to store a `DateTime` object results in a exception `SQLSTATE[HY000]: General error: 1 unrecognized token: "01T23"`

This is because the escapeDateTime() method simply creates an unescaped string in `Y-m-d\TH:i:s.u\Z` format.

Overriding this method in `Dbal/Sqlite` like this fixes inserting:

```php
    protected function escapeDateTime(\DateTime $value)
    {
        return $this->escapeString(parent::escapeDateTime($value));
    }
```
However trying to access the datetime field after saving no longer returns the proper type:

```php
$e = new Entitiy();
$e->dt = new \DateTime();
var_dump($e->dt);
// class DateTime#26 (3) {
//   public $date =>
//   string(26) "2017-10-27 11:00:22.660608"
//   public $timezone_type =>
//   int(3)
//   public $timezone =>
//   string(13) "Europe/Berlin"
// }
$e = $e->save();
var_dump($e->dt);
// string(27) "2017-10-27T09:00:22.660608Z"
```

Once the object is refetched from the database, the type is correct though. I think this might be a general problem and not even limited to SQLite. 

However back to SQLite, according to the [SQLite Affinity rules](https://sqlite.org/datatype3.html#affinity_name_examples), a DATETIME should be numeric so storing it as timestamp makes more sense:

```php
    protected function escapeDateTime(\DateTime $value)
    {
        return $value->getTimestamp();
    }
```

This of course doesn't translate back to a DateTime object at all. I think the current type system needs to be adjusted to be database type specific?

PS: thanks for writing this library.

**Comment by tflori** [comment]
@splitbrain thanks for your contribution. I will have look at this on the weekend - this should also affect mysql and postgres (they need strings too)

The type conversions are just for converting to sql. It was not planned to have it automatically converted to the appropriate type.

I have a trait in my application for converting these values:
```php
<?php

namespace App\Model;

use ORM\Entity;

trait CreatedTrait
{
    /**
     * Get a DateTime object from created
     *
     * @return \DateTime|null
     */
    public function getCreated()
    {
        if (!$this instanceof Entity) {
            return null;
        }

        $col = static::getColumnName('created');

        if (!isset($this->data[$col])) {
            return null;
        }

        return new \DateTime($this->data[$col]);
    }

    /**
     * Set created to $dt or 'now'
     *
     * @param \DateTime|null $dt
     * @return $this
     */
    public function setCreated(\DateTime $dt = null)
    {
        if (!$this instanceof Entity) {
            return $this;
        }

        $col = static::getColumnName('created');

        if (isset($this->data[$col])) {
            return $this;
        }

        $dt = $dt ?? \DateTime::createFromFormat('U.u', microtime(true))
                              ->setTimezone(new \DateTimeZone('UTC'));
        $this->data[$col] = $dt->format('Y-m-d\TH:i:s.u\Z');

        return $this;
    }
}
```

And another one:
```php
<?php

namespace App\Model;

use ORM\Entity;

trait UpdatedTrait
{
    /**
     * Get a DateTime object from created
     *
     * @return \DateTime|null
     */
    public function getUpdated()
    {
        if (!$this instanceof Entity) {
            return null;
        }

        $col = static::getColumnName('updated');

        if (!isset($this->data[$col])) {
            return null;
        }

        return new \DateTime($this->data[$col]);
    }

    /**
     * Set created to $dt or 'now'
     *
     * @param \DateTime|null $dt
     * @return $this
     */
    public function setUpdated(\DateTime $dt = null)
    {
        if (!$this instanceof Entity) {
            return $this;
        }

        $col = static::getColumnName('updated');

        $dt = $dt ?? \DateTime::createFromFormat('U.u', microtime(true))
                              ->setTimezone(new \DateTimeZone('UTC'));
        $this->data[$col] = $dt->format('Y-m-d\TH:i:s.u\Z');

        return $this;
    }

    public function preUpdate()
    {
        $this->setUpdated();

        if (is_callable('parent::preUpdate')) {
            parent::preUpdate();
        }
    }
}
```

**Comment by tflori** [comment]
I'm wondering about sqlites datetime handling. You can store integers (timestamps) and date time strings. Maybe other DBMS allow this too but I know from postgres and mysql that they return an iso formatted string where sqlite returns what you inserted:

```console
$ sqlite3 /tmp/test.sqlite "SELECT * FROM A;"                                                                                                                                                                                                                 Sa 28 Okt 2017 16:12:26 CEST
2017-01-01T00:00:00Z
1483228800
```

The conversion of `DateTime` into ISO string is just syntax sugar. So you can just give a column a DateTime value. If you want your DBAL to escape DateTime different you can provide your own:

```php
<?php

class MyDbal extends \ORM\Dbal\Sqlite
{
  protected function escapeDateTime(\DateTime $value)
  {
    return $value->getTimestamp(); // this does not have microseconds
  }
}

$em = new \ORM\EntityManager([\ORM\EntityManager::OPT_DBAL_CLASS => '\MyDbal']);
```

Values don't get converted from database to appropriate types in php. Doctrine (at least version 2.1) is converting all value in his hydrator. That's the reason why you should not use doctrine for batch scripts, fetch partial objects and so on.. The problem would be that you converting a string (the database always returns a string for date time values) to a `DateTime` object even if you don't need this value.

:thinking: We really could add something like this by storing the data from [getColumnMeta()](http://php.net/manual/de/pdostatement.getcolumnmeta.php) to the entity or a converter object and call this in the getter. But this is a new feature that needs some concepts first.

**Comment by tflori** [comment]
version 1.2.1 has this bugfix inside and version 1.3 will also include the feature for `isset`.

if you still encounter any problems feel free to reopen the issue
