### ISSUE TITLE
Type Hints incomplete

### ISSUE THREAD

**Issue by splitbrain** [tflori/orm#50]
I have code like this which should be correct according to the documentation and is also just working fine:

```php
$products = $db->fetch(Product::class)->where('fetchurl', '!=', '')->all();
```
However my IDE (Intellij IDEA, should be the same in PHPStorm) complains about the `all()` call:

> Method 'all' not found in \ORM\QueryBuilder\Parenthesis|\ORM\QueryBuilder\ParenthesisInterface

Not only does it litter my code with false positive warnings it also breaks auto completion.

It would be great if the correct return types could be added to the methods - I guess it's EntityFetcher?.

**Comment by splitbrain** [comment]
Actually I think the problem is the ``@return self`` in ParenthesisInterface. It should be ``@return $this``. This seems to fix the problem for me.

**Comment by tflori** [comment]
Can you try if ’@return static’ works too?

Andreas Gohr <notifications@github.com> schrieb am Sa., 29. Sep. 2018,
11:12:

**Comment by tflori** [comment]
:+1: can you provide a PR? then I cam release a mew version today. otherwise you will get it next Friday because I will be on a hiking trip till Thursday
