### ISSUE TITLE
Feature : An optional where clause in relations?

### ISSUE THREAD

**Issue by flavi1** [tflori/orm#68]
Hello.
First, thank you for this great ORM!

### An optional where clause in relations?

Example : 3 tables articles, categories, tags.
We want tags to be linked with any kind of tables with only one extra table "tags_jointures" with columns "id_tag", "id_object", and "object_table_name" (or "scope"...)

Then we can join category 3 with tag 1 by inserting in tags_jointures : 
id_tag=1, id_object=3, scope=categories.

Now we can join article 5 with tag 1 by inserting in tags_jointures : 
id_tag=1, id_object=5, scope=articles.

Maybe, it can be achieved by adding a Relation::OPT_WHERE_CLAUSE new option to implement at least one where condition in the junction's query?

Best regards

**Comment by tflori** [comment]
So you want to define a relation "tags" on `Article` and `Category` that link to the tags but you have to exclude other entries in that table? That is one direction.

Do you want to have also a relation "usedBy" in `Tag` that then returns an array with categories and articles, or will it there also be a relation "articles" with an additional where clause?

The thing is that these "morphed" relations would need 2 or more complete new relation types. I also thought about this relation types since I'm using Eloquent (the laravel ORM) at work. Sometimes they are really helpful but they have a lot of bugs in laravel and I don't know how complicated I would get here.

Adding a where clause to a many to many query would be easier indeed. But there is another way to solve that without changing the code at all and also your DBMS will be happier because you can define foreign keys for it: create two tables: `article_tags` and `categories_tags`. You can then define: if an `article` gets deleted the corresponding `article_tags` should also be deleted.

For additional where clause we should also think about that for a one-to-many relation and what that would mean:

- extending the short form declaration (maybe an assoc key `where` that is excluded from the count) https://github.com/tflori/orm/blob/a66da2cc098ce5c58e0dd8667980fa171fa0ebdf/src/Relation.php#L84
- setRelated has to set the columns from where condition too (can/must we deal with expressions instead of constants?)
- all joins and fetch methods have to be extended to use the where conditions (the complexity might get too high and decrease the maintainability)

Pros and cons:

- + It is much easier than introducing morph relations
- +/- It allows the developer to work with a legacy database design (it should be migrated to a better design instead)
- - it increases the complexity of an already complex part of the library (relations)

**Comment by flavi1** [comment]
Sorry for confusion. I'm wrong because my example is bad.
- First, your relation strategy doesn't have to be more complex. Your library is as simple as possible, and this is the reason that makes your library as good it is.
- But, regardless trying to extend relations mechanism (witch is absolutely not necessary), it would be really interesting to be able to add : 

>  * AND/OR Where clauses (ex : active=1, date_creation > 01/01/2015, ...)
>  * Limit / Offset to manage pagination
>  * order by ASC/DESC


Not sure but...
Then, from the Entity::__get() method, in case of relations, what we want is a QueryBuilder object. (BREAKING CHANGE)
I suggest to get the non-fetched relation object (but, consequently, without the Entity::getRelated stored cache form "trait Relations"...) If we got a ready to use EntityFetcher object instead of the result set, we will be able to add any constraints we want. (Bonus : Maybe we can add a stored cache in the EntityFetcher instead of the "Entity::getRelated" one)

**Comment by flavi1** [comment]
I assume that using getRelation() instead of getRelated() in Entity::getAttribute() should be technically enough.

Maybe not enough elegant, because we will have to pass the obtained relation object from Entity to Entity itself. (Is it bad?)

Finally, because it's a breaking change feature, it will need to be implemented in a next version... (If you firstly want to valid this)

**Comment by flavi1** [comment]
For elegance, we can return a new object "fetchableRelation" to wrap relation, entity, and boolean getAll property.
Something like that : 

```
class fetchableRelation {

    function __construct($entity, $relation, $getAll = false) {...}

    function getRelation() {...}

    function getEntity() {...}

    function expectedOne() { return !$this->getAll; }
}

```

**Comment by tflori** [comment]
now I understand that you maybe missed a part from the documentation:

> But for relations with cardinality many you will receive an array from getter and an `EntityFetcher` from fetch.

Maybe we have to point out that it is exactly for such usecases: you can add limit offset, additional where conditions etc...

https://tflori.github.io/orm/relations.html

**Comment by tflori** [comment]
and you can setup specific relations with that too:

```php
public function getTags()
{
  return $this->fetch('tags')->where('scope', 'article')->all();
}
```

But as said: the better way would be to implement morphed relations.

**Comment by flavi1** [comment]
Hum.. Yes i missed this part of documentation, thanks...
(note for me) : TODO : Learn to read a documentation. (lol)

But you said that implement morphed relations will increase code complexity, and i totally agree with you.

Please wait a little time because i think it's possible to get around this problem.
I will write a little Entity extension by using two getters : the __get() magic method and the ArrayAccess::offestGet(). One for QueryBuilders (EntityFetcher) by reference, and the other to automatically get fetched result (returning the 'one' or the 'many' method, depending of relations settings...)
Then it's not needed to implement morphed relations because we can easily inject dynamically where/limit/orderBy/... constraints.

Examples : 
$article['tags']->where('active', '1');
if($article->tags ==  $article['tags']->where('active', '1')->all())
    echo 'many, not morphed, but active!';

$article['category_parent']->where('cat_type', 'article');
if($article->tags ==  $article['category_parent']->where('cat_type', 'article')->one())
    echo 'one, morphed!';

In a second time, we can create a static property Entity::$constraints to list initial where OR/AND clauses, limit, offset, orderBy DESC/ASC, for each columns, and automatically apply it. More flexible (because not only concerns morphed relations), no need to modify your simple and easy to maintain actual code, as it can be just upper than the Entity class.......

**Comment by flavi1** [comment]
But not sure that EntityFetcher can actually be passed by reference...?

**Comment by tflori** [comment]
every object will be passed by reference (kind of): https://www.php.net/manual/en/language.oop5.references.php

I don't get the idea of your workaround. We already have a `Entity::__get()` method that returns the fetched objects and a `Entity::fetch()` method that returns an `EntityFetcher` (by reference so to say).

Default where conditions per entity and per relation still make sense. If you can come up with a pull request we can have a look at it.

**Comment by tflori** [comment]
I'm currently implementing this feature with filters: https://github.com/tflori/orm/tree/feature-filters

The filters can be registered globally for an entity, added to an instance of fetcher or registered for a relation.

**Comment by tflori** [comment]
This feature might help you more than filters: https://github.com/tflori/orm/blob/51f5027fae85487264948519c90fbd6c06b40905/docs/relationDefinition.md#morphed-relation-1

You can give it a try with `composer require tflori/orm:dev-f/morphed-relations` and defining your entities like this:

```php
<?php

use ORM\Entity;

class Tag extends Entity
{
    protected static $relations = [
        'jointures' => [TagJointure::class, 'tag'],
    ];
}

class TagJointure extends Entity
{
    protected static $relations = [
        'tag' => [Tag::class, ['id_tag' => 'id']],
        'entity' => [['scope' => [
            'categories' => Category::class,
            'articles' => Article::class,
        ], ['id_object']],
    ];
}

class Category extends Entity
{
    protected static $relations = [
        'tags' => [TagJointure::class, 'entity'],
    ];
}

class Article extends Entity
{
    protected static $relations = [
        'tags' => [TagJointure::class, 'entity'],
    ];
}
```

Then you can access the tags of an Article like that:

```php
$article = $em->fetch(Article::class)->one();
$tags = $article->tags;

// load all tags with one query
$em->fetch(Tag::class)->whereIn('id', array_map(function (TagJointure $jointure) {
    return $jointure->id_tag;
}, $tags));

foreach ($tags as $jointure) {
  echo $jointure->tag->name;
}
```

I would appreciate a feedback.

**Comment by flavi1** [comment]
Hello.

I can't test it now, but reading the doc, i really like the fact that, with morphed relation, you doesn't have to completely define the relation from the two linked objects.
( 'jointures' => [TagJointure::class, 'tag'] expression target to 'tag' => [Tag::class, ['id_tag' => 'id']] is enough)
Result : ['id_tag' => 'id'] is written once, in one class, so there is no redundancy in relations definition.

In addition the filter implementation, with ability to use closure, callable, or class instance that implements FilterInterface seems to be really great flexible and simple.

I think, before your ORM, a PHP KISS but complete and flexible ORM was a big lack.
I will use it in a near future, for sure.
Thank you for it!

**Comment by tflori** [comment]
Thanks for your feedback. I think we can close it now. Feel free to open a new issue if something is not working as expected.
