### ISSUE TITLE
Warning: Undefined variable $fromClause in UpdateFromStatement.php on line 22

### ISSUE THREAD

**Issue by flavi1** [tflori/orm#78]
With the last release :

Sometimes, I got the warining "Undefined variable $fromClause in UpdateFromStatement.php on line 22"
Regarding to the code, this happens when there is no jointures.

put `$fromClause = '';` on top of buildUpdateFromStatement function resolve the issue.

Best regards.

**Comment by tflori** [comment]
good find. seems a test is necessary

**Comment by tflori** [comment]
it is fixed in dev-master. next release will include the fix

**Comment by tflori** [comment]
hey, I created a new release v1.10.0-rc.1 with a fix for that. please confirm that your issues are solved and close the ticket. then I can create the release

**Comment by flavi1** [comment]
My issues are solved with this RC. Thank you
