### ISSUE TITLE
Method "fetch" missing?

### ISSUE THREAD

**Issue by FloKnapp** [tflori/orm#8]
I´m currently implementing your solution and after struggling with composer i got it finally to a point where i can include/use the EntityManager. Now i want to fetch a table by my entity but i can't find the 'fetch' method anywhere... As your documentation is saying this is how i can access my database. It's just a question, maybe i'm doing something wrong... but i followed strictly your implementation guidelines.

Thank you in advance for any help :-)

Flo

**Comment by tflori** [comment]
it is just not implemented yet. there is a reason why there is still no
alpha version. the `EntityFetcher` is only working with raw SQL and only in
`dev-feature-entityFetcher`.

FloKnapp <notifications@github.com> schrieb am Sa., 10. Dez. 2016, 01:54:

**Comment by FloKnapp** [comment]
Great, thank you for your answer. I'll waiting patiently :)
