### ISSUE TITLE
Transaction management

### ISSUE THREAD

**Issue by flavi1** [tflori/orm#81]
I'm not sure if it's an issue. Maybe I just don't understand how to use transactions with your ORM.
With the following code, I got an uncaught PDOException: "There is already an active transaction"

```
class Comments extends ORM\Entity
{
	
	static public $definition = "CREATE TABLE 'comments' ('id' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 'id_article' INTEGER, 'title' INTEGER);";
	
    protected static $relations = [
        'article' => [Article::class, ['idArticle' => 'id']],
    ];
}

class Article extends ORM\Entity
{
	
	static public $definition = "CREATE TABLE 'article' ('id' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 'title' INTEGER);";
	
    protected static $relations = [
        'comments' => [Comments::class, 'article']
    ];
}


$article = new Article();
$article->title = 'An amazing title that points out nothing';
$article->save();

$em->getConnection()->beginTransaction();
	$comment = new Comments();
	$comment->title = 'An amazing comment';
	$comment->setRelated('article', $article);
	$comment->save();
$em->getConnection()->commit();
```

I use SQLite.
This will probably not happen with a nested transaction strategy as described here https://www.php.net/manual/en/pdo.begintransaction.php#116669

Does your ORM needs an extended PDO with nested transaction support?
Does your ORM should work with default PDO without nested transaction support?
I made a mistake?

**Comment by flavi1** [comment]
Sorry.
I just realized that it's related with https://github.com/tflori/orm/issues/72

**Comment by flavi1** [comment]
We may need to improve the documentation?
I suggest to create a void interface "nestedTransaction" just in order to say "my PDO implementation is compatible with nested transaction".
Or update the documentation to never use `$em->getConnection()->beginTransaction()` but only the wrapper `$em->beginTransaction()` ?

**Comment by tflori** [comment]
we definetly should update the documentation. at least we should use `$em->beginTransaction()`. maybe a paragraph in [entitites.md](https://github.com/tflori/orm/blob/master/docs/entities.md)

**Comment by tflori** [comment]
maybe like that?


### Creating entities and working in transactions

To create a new entity you can use the `new` keyword. This will create a new entity with the default values from the
entity definition. You can then modify the entity and save it to the database.

```php
$user = new User();
$user->email = 'john.doe@example.com';
$user->save();
```

To work in a transaction you can use the `EntityManager::beginTransaction()` method. This will start a transaction or 
create a savepoint if a transaction is already started. You can then commit or rollback the transaction.

```php
$entityManager->beginTransaction();
$user = new User();
$user->email = 'john.doe@example.com';
$user->save();
$activation = new UserActivation();
$activation->setRelated('user', $user);
$activation->code($code = bin2hex(random_bytes(8)));
$activation->save();
$entityManager->commit();
```

**Comment by flavi1** [comment]
There is a last little problem.
I think we are likely to break a feature.
ORM\EntityManager::OPT_CONNECTION allow us to use our own PDO implementation. We probably need a mecanism to prevent to bring nested transaction support on PDO implementation that already provide nested transaction support. I suggest to add an arbitrary void interface just in order to give the possibility to inform the ORM that nested transaction is already provided. Or just an option in the DBConfig?

I don't need nested transaction. I'm just thinking about possible confusion for other people. I mean, my first attempt when I see the "bug" was to create a PDO class that implements nested transaction. lol

**Comment by tflori** [comment]
If you provide your own customized PDO object then you know that you need an transaction counter and savepoints and you need to centralize this. If you centralized this through your PDO object - fine then use that to create and commit transactions. If you have another transaction handler use that. If you don't have use `$em->beginTransaction()` - if there is no awareness that there can only be one transaction from one connection you will not write your own transaction handler to work with savepoints.

If I'm not mistaken the ORM is nowhere beginning transactions - so only the implementation will start transactions. Therefore you can start your own transaction in your PDO connection without any issue.

One last thing: when you want EntityManager to use your own transaction handler you can define a DBAL class (extending one of `ORM\Dbal\*`) and implement it in `beginTransaction()` and `commit()`.

**Comment by flavi1** [comment]
`One last thing: when you want EntityManager to use your own transaction handler you can define a DBAL class (extending one of ORM\Dbal\*) and implement it in beginTransaction() and commit().`
Ok. It's clear. Nothing to add. Thank you
