### ISSUE TITLE
Add a delete method on Entity

### ISSUE THREAD

**Issue by flavi1** [tflori/orm#82]
For my personal use, I extends the Entity class

```
abstract class Entity extends \ORM\Entity {	

	public function delete() {
		return $this->entityManager->delete($this);
	}
	
}
```

It's not enough for a general prupose, but for me it's ok because for now, I don't use events.
It's just a sugar, and it's not absolutely usefull, since I can directly use the EventManager to do it, and I will probably have to unset the entity after delete it...
Not sure if it's a good idea.

**Comment by tflori** [comment]
the code is ok for the base entity object. Everything that needs to be done is done in entityManager. To have a default method in `Entity` makes sense - you might also want to overwrite it with a soft delete method like that:

```php
trait SoftDeletes
{
    public function delete()
    {
        $this->deleted_at = now();
        $this->save();
    }
    public function forceDelete()
    {
        parent::delete();
    }
}
````

**Comment by flavi1** [comment]
Hum...
You mean it's too much opinionated to consider that delete() method should use the entityManager, because someone can consider that a deleted db entry is just an entry with a non null deleted_at property for example?
I got it. And I agree.

**Comment by tflori** [comment]
Yes and no. It is ok to have a default method that is also triggering the deleting and deleted events. And it is good to have it because you can then implement your own way of deleting an entity and don't need to consider if this object is using another way of deleting it.
